import { useStore } from '~/store/index';

const store = useStore();

export const ready = computed(() => {
    return store.ready;
});

export const useLayout = () => {
    // Theme handling
    const themeCookie = useCookie<ThemesList>('theme', {
        path: '/',
        sameSite: 'lax',
        secure: true,
        maxAge: 60 * 60 * 24 * 360,
    });

    // Reactive theme reference
    store.theme = themeCookie.value ?? 'default';

    useHead(() => {
        const theme = store.theme ?? 'default';

        // calendryColors / calendryThemes are GENERATED by modules/styles.ts and
        // auto-imported. They are the only place the `*Rgb` entries exist.
        //
        // This previously read colorsList / themesList — the hand-written source
        // vocabulary those generated objects are built FROM, which holds plain
        // hex strings and no `*Rgb` keys at all. The filter therefore matched
        // nothing and `css` was always empty, so no custom property was ever
        // emitted and every themed color silently fell back to its compile-time
        // value. Reading the generator's output instead is the whole fix.
        const themeColors = theme === 'default'
            ? {}
            : ((calendryThemes as Record<string, Record<string, unknown>>)[theme] ?? {});

        const css = Object
            .entries({
                ...calendryColors,
                ...themeColors,
            })
            // Only the `*Rgb` entries become custom properties: the generated
            // SCSS resolves every color as rgb(var(--name, <fallback>)), so the
            // property must carry bare channels ("250, 250, 250"), not a color.
            .filter(([key]) => key.endsWith('Rgb'))
            .map(([key, value]) => `--${ key.replace('Rgb', '') }: ${ (value as number[]).join(',') }`)
            .join(';');

        return {
            titleTemplate(title) {
                if (!title) return 'Calendry';
                return `${ title } | Calendry`;
            },
            meta: [
                {
                    name: 'description',
                    content: '',
                },
            ],
            htmlAttrs: {
                lang: 'en',
                class: [`theme-${ theme }`],
            },
            style: [{
                key: 'pageStyles',
                innerHTML: `:root {${ css }}`,
            }],
        };
    });

    onNuxtReady(() => {
        setWindowStore();
        window.addEventListener('resize', setWindowStore);
    });

    onUnmounted(() => {
        window.removeEventListener('resize', setWindowStore);
    });
};


function setWindowStore() {
    store.isMobile = window.innerWidth < 700;
    store.isMobileOrTablet = window.innerWidth < 1466;
    store.isTablet = window.innerWidth < 1466 && window.innerWidth >= 700;
    store.isPC = window.innerWidth >= 1466;
    store.isPCWide = window.innerWidth >= 1900;
    store.scrollbarWidth = window.innerWidth - document.documentElement.offsetWidth;
    store.viewport.width = window.innerWidth;
}
