import { useStore } from '~/store/index';

/**
 * The store is resolved LAZILY, never at module scope.
 *
 * A module-level `const store = useStore()` runs the moment anything imports
 * this file. That happened to work while the only importer was `default.vue`,
 * which Nuxt evaluates after installing Pinia — but the instant a second module
 * imported it from an earlier point in the request (the nav registry, reached
 * from route middleware), SSR died with `getActivePinia() was called but there
 * was no active Pinia`. Pinia's own message said "This will fail in production".
 *
 * `computed` is lazy, so `ready` still evaluates inside whichever component
 * reads it, where Pinia is active.
 */
export const ready = computed(() => useStore().ready);

/**
 * The theme cookie, as one definition rather than two.
 *
 * `useCookie` needs the Nuxt instance, so anything that wants to *change* the
 * theme has to take this ref at setup time and close over it — calling it from
 * inside a click handler is the "composable called outside a setup function"
 * trap again.
 */
export const useThemeCookie = () => useCookie<ThemesList>('theme', {
    path: '/',
    sameSite: 'lax',
    secure: true,
    maxAge: 60 * 60 * 24 * 360,
});

/**
 * Flips between the light base and the dark theme, writing both the cookie
 * (which survives reload) and the store (which `useHead` reads to emit the
 * custom properties). Writing only one of them produces a page whose colours
 * and whose `theme-*` class disagree.
 */
export function useThemeToggle() {
    const themeCookie = useThemeCookie();
    const store = useStore();

    return () => {
        const next: ThemesList = store.theme === 'dark' ? 'default' : 'dark';

        themeCookie.value = next;
        store.theme = next;
    };
}

export const useLayout = () => {
    const store = useStore();

    // Theme handling
    const themeCookie = useThemeCookie();

    // Reactive theme reference
    store.theme = themeCookie.value ?? 'default';

    useHead(() => {
        const theme = store.theme ?? 'default';

        // calendryColors / calendryThemes are GENERATED by modules/styles.ts and
        // auto-imported. They are the only place the `*Rgb` entries exist.
        //
        // This previously read colorsList / themesList — the hand-written source
        // vocabulary those generated objects are built FROM, which holds plain
        // hex strings and no `*Rgb` keys at all. The filter therefore matched
        // nothing and `css` was always empty, so no custom property was ever
        // emitted and every themed color silently fell back to its compile-time
        // value. Reading the generator's output instead is the whole fix.
        const themeColors = theme === 'default'
            ? {}
            : ((calendryThemes as Record<string, Record<string, unknown>>)[theme] ?? {});

        const css = Object
            .entries({
                ...calendryColors,
                ...themeColors,
            })
            // Only the `*Rgb` entries become custom properties: the generated
            // SCSS resolves every color as rgb(var(--name, <fallback>)), so the
            // property must carry bare channels ("250, 250, 250"), not a color.
            .filter(([key]) => key.endsWith('Rgb'))
            .map(([key, value]) => `--${ key.replace('Rgb', '') }: ${ (value as number[]).join(',') }`)
            .join(';');

        return {
            titleTemplate(title) {
                if (!title) return 'Calendry';
                return `${ title } | Calendry`;
            },
            meta: [
                {
                    name: 'description',
                    content: '',
                },
            ],
            htmlAttrs: {
                lang: 'en',
                class: [`theme-${ theme }`],
            },
            style: [{
                key: 'pageStyles',
                innerHTML: `:root {${ css }}`,
            }],
        };
    });

    onNuxtReady(() => {
        setWindowStore();
        window.addEventListener('resize', setWindowStore);
    });

    onUnmounted(() => {
        window.removeEventListener('resize', setWindowStore);
    });
};


function setWindowStore() {
    const store = useStore();

    store.isMobile = window.innerWidth < 700;
    store.isMobileOrTablet = window.innerWidth < 1466;
    store.isTablet = window.innerWidth < 1466 && window.innerWidth >= 700;
    store.isPC = window.innerWidth >= 1466;
    store.isPCWide = window.innerWidth >= 1900;
    store.scrollbarWidth = window.innerWidth - document.documentElement.offsetWidth;
    store.viewport.width = window.innerWidth;
}
